[package]
name = "riscv_vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elf_load = { path = "../elf_load/" }
pollster = "0.3.0"
wgpu = "0.18.0"
wgpu_text = "0.8.5"
winit = "0.28"
