name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        run: cargo build --verbose

      - run: |
          mkdir artifacts
          cp target/debug/riscv_vm artifacts/
          cp examples/os.elf artifacts/

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: riscv_vm
          path: artifacts/

  build_vga:
    name: BuildWithVga
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        run: cargo build --features vga_text_buf --verbose

      - run: |
          mkdir artifacts_vga
          cp target/debug/riscv_vm artifacts_vga/
          cp examples/os_vga.elf artifacts_vga/

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: riscv_vm_vga
          path: artifacts_vga/
